import { useState, useCallback } from 'react';
import { getTopicName } from '../../data/curriculum';

const THEME_CSS = {
  'Rainbow Bright': { page: '#fff', accent: '#e11d48', header: '#7c3aed', font: 'Nunito' },
  'Space Galaxy': { page: '#f8fafc', accent: '#6366f1', header: '#1e1b4b', font: 'Poppins' },
  'Ocean Adventure': { page: '#f0fdfa', accent: '#0d9488', header: '#0f766e', font: 'Quicksand' },
  'Jungle Safari': { page: '#f7fee7', accent: '#65a30d', header: '#3f6212', font: 'Nunito' },
  'Superhero': { page: '#fef2f2', accent: '#dc2626', header: '#1e3a5f', font: 'Poppins' },
  'Dinosaur World': { page: '#fff7ed', accent: '#d97706', header: '#78350f', font: 'Nunito' },
  'Sports': { page: '#eff6ff', accent: '#2563eb', header: '#1e3a5f', font: 'Poppins' },
};

function downloadPDF(text, theme, title) {
  const colors = THEME_CSS[theme] || THEME_CSS['Rainbow Bright'];
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title} — Lesson Prompt</title>
  <link href="https://fonts.googleapis.com/css2?family=${colors.font}:wght@400;600;700&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: '${colors.font}', system-ui, sans-serif;
      font-size: 13px;
      line-height: 1.7;
      color: #1e293b;
      background: ${colors.page};
      padding: 40px;
    }
    .header {
      text-align: center;
      margin-bottom: 32px;
      padding-bottom: 20px;
      border-bottom: 3px solid ${colors.accent};
    }
    .header h1 {
      font-size: 22px;
      font-weight: 700;
      color: ${colors.header};
      margin-bottom: 4px;
    }
    .header p {
      font-size: 12px;
      color: #64748b;
    }
    .content {
      max-width: 800px;
      margin: 0 auto;
      white-space: pre-wrap;
      word-wrap: break-word;
      font-family: 'Courier New', monospace;
      font-size: 12px;
      line-height: 1.6;
      color: #334155;
      background: #fff;
      padding: 28px;
      border-radius: 8px;
      border: 1px solid #e2e8f0;
    }
    .footer {
      text-align: center;
      margin-top: 28px;
      font-size: 10px;
      color: #94a3b8;
    }
    .badge {
      display: inline-block;
      padding: 2px 10px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 600;
      color: #fff;
      background: ${colors.accent};
      margin-bottom: 8px;
    }
    @media print {
      body { padding: 0; background: #fff; }
      .content { border: none; box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <span class="badge">${theme}</span>
    <h1>${title}</h1>
    <p>Lesson Prompt Generator — ${new Date().toLocaleDateString()}</p>
  </div>
  <div class="content">${escapeHTML(text)}</div>
  <div class="footer">Generated by Lesson Prompt Generator</div>
  <script>window.onload=function(){window.print()}</script>
</body>
</html>`;

  const w = window.open('', '_blank');
  w.document.write(html);
  w.document.close();
}

function escapeHTML(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export default function PreviewView({ promptData, onBack, onCopy, onSave, onRegenerate, copied, loading }) {
  const [editedText, setEditedText] = useState(promptData.promptText);
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    onSave({ ...promptData, promptText: editedText });
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleDownloadPDF = useCallback(() => {
    const title = `${promptData.grade} · ${promptData.subject} · ${getTopicName(promptData.topic)}`;
    downloadPDF(editedText, promptData.theme || 'Rainbow Bright', title);
  }, [editedText, promptData]);

  const isAI = promptData.promptMode === 'AI Generated';

  const chips = [
    promptData.grade,
    promptData.subject,
    getTopicName(promptData.topic),
    promptData.targetAI,
    promptData.lessonLength,
    promptData.studentLevel,
  ].filter(Boolean);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 transition-colors cursor-pointer"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to Generator
        </button>
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-semibold text-slate-800">Prompt Preview</h2>
          <span className={`px-2 py-0.5 rounded-md text-xs font-medium ${
            isAI ? 'bg-violet-100 text-violet-700' : 'bg-slate-100 text-slate-500'
          }`}>
            {isAI ? 'AI Generated' : 'Template'}
          </span>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={() => onCopy(editedText)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all cursor-pointer
              ${copied
                ? 'bg-emerald-500 text-white'
                : 'bg-primary-600 text-white hover:bg-primary-700'
              }`}
          >
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
          <button
            type="button"
            onClick={handleSave}
            className={`px-4 py-2 rounded-lg text-sm font-medium border transition-all cursor-pointer
              ${saved
                ? 'bg-emerald-50 text-emerald-600 border-emerald-200'
                : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
              }`}
          >
            {saved ? 'Saved!' : 'Save to History'}
          </button>
          <button
            type="button"
            onClick={handleDownloadPDF}
            className="px-4 py-2 rounded-lg text-sm font-medium border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 transition-all cursor-pointer"
          >
            Download PDF
          </button>
        </div>
      </div>

      <div className="flex flex-wrap gap-2">
        {chips.map((chip, i) => (
          <span key={i} className="px-2.5 py-1 rounded-md bg-primary-50 text-primary-700 text-xs font-medium">
            {typeof chip === 'object' && chip.arabic ? `${chip.arabic} — ${chip.english}` : chip}
          </span>
        ))}
      </div>

      <textarea
        value={editedText}
        onChange={(e) => setEditedText(e.target.value)}
        aria-label="Editable prompt text"
        className="w-full min-h-[500px] p-4 border border-slate-200 rounded-xl bg-white text-sm leading-relaxed text-slate-800 font-mono resize-y outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100"
        spellCheck={false}
      />

      <div className="flex justify-between items-center pt-2">
        <button
          type="button"
          onClick={onBack}
          className="text-sm text-slate-500 hover:text-slate-700 cursor-pointer"
        >
          Back to Generator
        </button>
        <div className="flex gap-2">
          {onRegenerate && (
            <button
              type="button"
              onClick={onRegenerate}
              disabled={loading}
              className={`px-4 py-2.5 rounded-lg text-sm font-medium border transition-all cursor-pointer ${
                isAI
                  ? 'border-violet-200 text-violet-600 hover:bg-violet-50 disabled:opacity-50'
                  : 'border-slate-200 text-slate-600 hover:bg-slate-50'
              }`}
            >
              {loading ? (
                <span className="flex items-center gap-1.5">
                  <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Regenerating...
                </span>
              ) : isAI ? 'Regenerate with AI' : 'Regenerate'}
            </button>
          )}
          <button
            type="button"
            onClick={() => onCopy(editedText)}
            className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all cursor-pointer
              ${copied
                ? 'bg-emerald-500 text-white'
                : 'bg-primary-600 text-white hover:bg-primary-700 shadow-md'
              }`}
          >
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
        </div>
      </div>
    </div>
  );
}
